QLBanHang/Models/SanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
       
        [Display (Name ="Mã sản phẩm")]
        public string MaSP { get; set; }
        [Display(Name = "Tên sản phẩm")]
        public string TenSP { get; set; }
        [Display(Name = "Đơn vị tính")]
        public string Donvitinh { get; set; }
        [Display(Name = "Đơn giá")]
        public Nullable<double> Dongia { get; set; }
        [Display(Name = "Loại sản phẩm")]
        public Nullable<int> MaLoaiSP { get; set; }
        [Display(Name = "Hình sản phẩm")]
        public string HinhSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
    }
}

QLBanHang/Controllers/GioHangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLBanHang.Models;
using System.Net;
using System.Net.Mail;

namespace QLBanHang.Controllers
{
    public class GioHangsController : Controller
    {
        private QLBanHangEntities db = new QLBanHangEntities();
        // GET: GioHangs
        public ActionResult Index()
        {
            List<CartItem> gioHang = Session["gioHang"] as List<CartItem>;
            return View(gioHang);
        }
        public RedirectToRouteResult AddToCart(String MaSP)
        {
            if (Session["gioHang"] == null)//chưa tồn tại=>tạo biến session để lưu sản phẩm vào giỏ hàng
            {
                Session["gioHang"] = new List<CartItem>();
            }
            //cập nhập/thêm
            List<CartItem> gioHang = Session["gioHang"] as List<CartItem>;
            // Kiểm tra gioHang đã có sp đang chọn(MaSP), nếu ch có => thêm
            if(gioHang.FirstOrDefault(c => c.MaSP== MaSP)== null)
            {
                SanPham sp = db.SanPhams.Find(MaSP);//Truy vấn bản sp để lấy thông tin sp
                CartItem newCart = new CartItem();
                newCart.MaSP = MaSP;
                newCart.TenSP = sp.TenSP;
                newCart.SoLuong = 1;
                newCart.DonGia = Convert.ToDouble(sp.Dongia);
                gioHang.Add(newCart);
            }
            else//SP đã có  trong giỏ hang ==> tăng sô lượng lên 1 
            {
                CartItem item = gioHang.FirstOrDefault(c => c.MaSP == MaSP);// tìm phần tử trong giỏ hàng
                item.SoLuong++;
            }
            Session["gioHang"] = gioHang;
             
            return RedirectToAction("index");
        }
        public RedirectToRouteResult Update(String MaSP, int txtSoLuong)
        {
            List<CartItem> gioHang = Session["gioHang"] as List<CartItem>;
            CartItem item = gioHang.FirstOrDefault(c => c.MaSP == MaSP);
            if (item != null)
            {
                item.SoLuong = txtSoLuong;
                Session["gioHang"] = gioHang;
            }
            return RedirectToAction("Index");
        }
        public RedirectToRouteResult Delete(String MaSP)
        {
            List<CartItem> gioHang = Session["gioHang"] as List<CartItem>;
            CartItem item = gioHang.FirstOrDefault(c => c.MaSP == MaSP);
            if (item != null)
            {
                gioHang.Remove(item);
                Session["gioHang"] = gioHang;
            }
            return RedirectToAction("Index");
        }
        public RedirectToRouteResult Order(String Email, string Phone)
        {
            List<CartItem> gioHang = Session["gioHang"] as List<CartItem>;
            string sMsg = "<html><body><table boder='1'><caption>Thông tin đặt hàng</caption>" +
                "<tr> <th>STT</th> <th>Tên hàng</th> <th>Số lượng</th> <th>Đơn giá</th> <th>Thành tiền</th> </tr>";
            int i = 0;
            double tongTien = 0;
            foreach(CartItem item in gioHang)
            {
                i++;
                sMsg += "<tr>";
                sMsg += "<td>" + i.ToString() + "</td>";
                sMsg += "<td>" + item.TenSP + "</td>";
                sMsg += "<td>" + item.SoLuong.ToString() + "</td>";
                sMsg += "<td>" + item.DonGia.ToString()+ "<t/d>";
                sMsg += "<td>" + String.Format("{0:0,###}", item.ThanhTien) + "<td>";
                sMsg += "</tr>";
                tongTien += item.ThanhTien;
            }
            sMsg += "<tr><th colspan='5'>Tổng cộng: " + string.Format("{0:0,###}", tongTien) + "</th></tr></table></body></html>";
            MailMessage mail = new MailMessage("1851050134thien@ou.edu.vn", Email, "Thông tin đơn hàng", sMsg);
            SmtpClient client = new SmtpClient("smtp.gamil.com", 587);
            client.EnableSsl = true;
            client.Credentials= new NetworkCredential("NguyenMinhThien", "241803229");
            mail.IsBodyHtml = true;
            client.Send(mail);
            ViewBag.SendMail = "Đặt hàng thành công";
            return RedirectToAction("Index");
        }
    }
}

QLBanHang/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLBanHang.Models;
using System.IO;

namespace QLBanHang.Controllers
{
    public class SanPhamsController : Controller
    {
        private QLBanHangEntities db = new QLBanHangEntities();

        // GET: SanPhams
        public ActionResult Index()
        {
            var sanPhams = db.SanPhams.Include(s => s.LoaiSP);
            return View(sanPhams.ToList());
        }

        // GET: SanPhams/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs, "MaLoaiSP", "TenLoaiSP");
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSP,TenSP,Donvitinh,Dongia,MaLoaiSP,HinhSP")] SanPham sanPham, HttpPostedFileBase HinhSP)
        {
            if (ModelState.IsValid)
            {
                if (HinhSP != null && HinhSP.ContentLength > 0)
                {
                    string filename = Path.GetFileName(HinhSP.FileName);
                    string path = Server.MapPath("~/Images/" + filename);
                    sanPham.HinhSP = "Images/" + filename;
                    HinhSP.SaveAs(path);
                }
                db.SanPhams.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs, "MaLoaiSP", "TenLoaiSP", sanPham.MaLoaiSP);
            return View(sanPham);
        }

        // GET: SanPhams/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs, "MaLoaiSP", "TenLoaiSP", sanPham.MaLoaiSP);
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSP,TenSP,Donvitinh,Dongia,MaLoaiSP,HinhSP")] SanPham sanPham, HttpPostedFileBase HinhSP)
        {
            if (ModelState.IsValid)
            {
                if (HinhSP != null && HinhSP.ContentLength > 0)
                {
                    string filename = Path.GetFileName(HinhSP.FileName);
                    string path = Server.MapPath("~/Images/" + filename);
                    sanPham.HinhSP = "Images/" + filename;
                    HinhSP.SaveAs(path);
                }
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs, "MaLoaiSP", "TenLoaiSP", sanPham.MaLoaiSP);
            return View(sanPham);
        }

        // GET: SanPhams/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            //Xóa tập tinh trong thư mục
            System.IO.File.Delete(Server.MapPath("~/" + sanPham.HinhSP));
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLBanHang/Views/SanPhams/Create.cshtml
@model QLBanHang.Models.SanPham


<h3>Thêm sản phẩm</h3>


@using (Html.BeginForm("Create","SanPhams",FormMethod.Post, new { enctype ="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Donvitinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Donvitinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Donvitinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dongia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dongia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dongia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLoaiSP, "MaLoaiSP", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiSP", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("HinhSP", "", new {Type="file"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QLBanHang/Views/SanPhams/Delete.cshtml
@model QLBanHang.Models.SanPham
@using QLBanHang.Models

<h3>Xóa sản phẩm nay</h3>


<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Donvitinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Donvitinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dongia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dongia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhSP)
        </dt>

        <dd>
            @Html.Image("../../"+ Model.HinhSP, "80", "100","")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiSP.TenLoaiSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSP.TenLoaiSP)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>

QLBanHang/Views/SanPhams/Details.cshtml
@model QLBanHang.Models.SanPham
@using QLBanHang.Models;
@{
    ViewBag.Title = "Details";
}

<h2>Chi tiết sản phẩm</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Donvitinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Donvitinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dongia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dongia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiSP.TenLoaiSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSP.TenLoaiSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhSP)
        </dt>

        <dd>
            @Html.Image("../../" + Model.HinhSP, "120", "150", "")
        </dd>


        <dt>
           
        </dt>

        <dd>
            <pr/>
            <a class="btn btn-info" href="@Url.Action("AddToCart", "GioHangs", new {MaSP = Model.MaSP})"><span class=" glyphicon glyphicon-shopping-cart""> Add</span></a>
            <a class="btn btn-info"href="@Url.Action("index", "Home")" >Quay lại</a>
        </dd>

    </dl>
</div>

QLBanHang/Views/SanPhams/Edit.cshtml
@model QLBanHang.Models.SanPham
@using QLBanHang.Models

<h3>Chỉnh sửa sản phẩm</h3>


@using (Html.BeginForm("Edit", "SanPhams", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaSP)

        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Donvitinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Donvitinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Donvitinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dongia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dongia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dongia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLoaiSP, "MaLoaiSP", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiSP", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Image("../../"+ Model.HinhSP, "80","100","")
                @Html.TextBox("HinhSP", "", new { type = "file" })
                @Html.Hidden("HinhSP")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QLBanHang/Views/SanPhams/Index.cshtml
@model IEnumerable<QLBanHang.Models.SanPham>
@using QLBanHang.Models

<h3>Danh mục sản phẩm</h3>

<p>
    @Html.ActionLink("Thêm sản phẩm", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenSP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Donvitinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dongia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HinhSP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LoaiSP.TenLoaiSP)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TenSP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Donvitinh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dongia)
        </td>
        <td>
            @Html.Image("../../"+ item.HinhSP, "40","50", "")
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LoaiSP.TenLoaiSP)
        </td>
        <td>
            @Html.ActionLink("Sửa", "Edit", new { id=item.MaSP }) |
            @Html.ActionLink("Xem chi tiết", "Details", new { id=item.MaSP }) |
            @Html.ActionLink("Xóa", "Delete", new { id=item.MaSP })
        </td>
    </tr>
}

</table>